set nocompatible
set nu
syntax enable

source ~/.dotfiles/vim/conf/vundle.vim
source ~/.dotfiles/vim/conf/vim-airline.vim
source ~/.dotfiles/vim/conf/nerdtree.vim

if has('gui_running')
    set background=light
else
    set background=dark
endif

let g:solarized_termcolors=256
colorscheme solarized

" Soft tabs {
  set smartindent
  set autoindent
  filetype indent on
  set tabstop=2
  set softtabstop=2
  set shiftwidth=2
  set expandtab
" }

"set leader key
let mapleader=","

set list
set listchars=tab:›\ ,trail:•,extends:#,nbsp:. " Highlight problematic whitespace

"set foldmethod=ident
"
set mouse=a

:nnoremap <Leader>q :Bdelete<CR>
