source ~/.vim/conf/general.vim
source ~/.vim/conf/vundle.vim
source ~/.vim/conf/ui.vim
source ~/.vim/conf/vim-airline.vim
source ~/.vim/conf/nerdtree.vim
source ~/.vim/conf/syntastic.vim
" Soft tabs {
  set smartindent
  set autoindent
  filetype indent on
  set tabstop=2
  set softtabstop=2
  set shiftwidth=2
  set expandtab
" }

set list
set listchars=tab:›\ ,trail:•,extends:#,nbsp:. " Highlight problematic whitespace

let g:neocomplcache_enable_at_startup = 1
nnoremap <Leader>q :Bdelete<CR>
